name: CI/CD
on: [ push ] # tells github to run this on any push to the repository
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # we tell Github to only execute this step if we're on our master branch (so we don't put unfinished branches in production)
    strategy:
          matrix:
           node: [ 16 ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json' # THIS PATTERN did the trick for me.
      - run: npm install --save
      - run: git config --global user.email "gilberto.tec@vivaldi.net"
      - run: npm run deploy
